### ISSUE TITLE
getMe does not work

### ISSUE THREAD

**Issue by noahgamboa** [jakemmarsh/node-soundcloud#11]
`{ message: 'Invalid path: me.json' }`

 is returned when I call 

`SC.getMe(callback)`

I definitely have a valid oauth_token so I'm not really sure what the problem is. I'll make a pr if i find something

**Comment by noahgamboa** [comment]
using this resolved the issue
`SC.get('/me', function(err, user) {})`

**Comment by jakemmarsh** [comment]
Thanks for the heads up. Fixed in 3ba82de526e403e576a7963b820ac7ca975a7c70
