### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by j4mesjung** [jakemmarsh/node-soundcloud#5]
```
var SC = require('node-soundcloud');

module.exports = function (app) {

  var client_id = "my client id";
  var secret = "my secret";

  SC.init({
    client_id: client_id,
    secret: secret
  });

  app.get('/users/:username', function (req, res) {

    SC.get('/resolve?url=https://soundcloud.com/' + req.params.username).then(function (data) {
      res.json({
        username: data.username
      });
    }).catch(function (err) {
      res.json({
        error: err
      });
    });

  });

};
```

this is returning 

```
GET /users/hypetrak 500 3.367 ms - 1247
TypeError: Cannot read property 'then' of undefined
```

but when i test out the web api on postman I get a JSON object.  Any help with this please?

**Comment by jakemmarsh** [comment]
You're calling `.then` after `SC.get` as if it returns a promise, but it does not. You should be providing a callback function instead, as outlined in the documentation:

``` js
SC.get('/resolve?url=https://soundcloud.com/' + req.params.username, function(err, data) {
   if ( err ) {
      res.json({ error: err });
   } else {
      res.json({ username: data.username });
   }
});
```

**Comment by BE4R** [comment]
hey jake,

sorry to bother you but I would appreciate any help!

so this is what i have in my node.js routes file with your suggestion

https://gist.github.com/BE4R/c5b685cf43ec0e9d943a

i test my api on postman and on the browser and it always returns

{
  "error": {}
}

I thought that Soundcloud returns a promise that we can then chain with
.then?

thanks,

James

**Comment by BE4R** [comment]
nevermind, disregard I fixed it.  Thanks :)
